### ISSUE TITLE
Feature Request - Automated Duo login

### ISSUE THREAD

**Issue by ruzickap** [FreshSupaSulley/Duochrome#9]
Hello.

Thank you for a great plugin - it is really handy :-)

Would it be possible to add one more setting to the Duochrome, which will allow me to automatically approve a single push request without clicking on the Duochrome icon?

The result of this setting is to automatically approve any incoming push request without user interaction - which can be handy for testing.
(this should "bypass" the Duo authentication)

Something like "Zero-Click Login"...

Thank for considering it.

**Comment by FreshSupaSulley** [comment]
Good idea. There used to be an "auto-login" feature that did this, but it was scrapped because it only worked on one duo subdomain. I imagine I could add it back to work for all. I'm thinking if you successfully login with Duochrome, the success screen will show an optional button for Auto Login, where the next time you visit that page again, it automatically starts checking and approving logins. I'll look into it, thanks

**Comment by ruzickap** [comment]
Thank you for your quick response.
The suggested solution is great :-)
Thanks...

**Comment by FreshSupaSulley** [comment]
Added this feature in 1.4.0, sorry it took so long. There's now a slider at the top of settings dictating the number of clicks necessary to log you in. Sliding it to the left will set it to "Zero-click login", where Duochrome will attempt to log you in 7 times whenever you navigate to a Duo API website. Let me know if this can be improved.

**Comment by ruzickap** [comment]
Excellent idea.
Works great thank you...
